### ISSUE TITLE
Installation trouble with "wheels"

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/MAVProxy#379]
Fresh install on Ubuntu 16.04 (LTS):
- and a second run find nothing to do..
- screenshots because it's a virtual machine...

![screenshot from 2017-02-12 20-02-43](https://cloud.githubusercontent.com/assets/1468842/22865143/3f7c29ba-f15e-11e6-9b37-a8c37ed9aaae.png)

![screenshot from 2017-02-12 20-02-18](https://cloud.githubusercontent.com/assets/1468842/22865146/439b99d6-f15e-11e6-86c8-99b0cb015442.png)

**Comment by khancyr** [comment]
@AndKe It is known pymavlink problem... But the install should be find even if the first build step failed for pymavlink. The install is good so everything should work as expected.
I am award of this problem... I am sorry I didn't find the time to work on that yet ... The issue is that pymavlink is building the mavlink header at the pip build phase and need future and lxml for that. Even if pip dl them they are not available at build phase, so it need to wait the install phase to success !

**Comment by AndKe** [comment]
ok, good to know, yes, as far I could test it worked fine, but I was not
sure if there would be some future problems due to that.

**Comment by amilcarlucas** [comment]
try `python setup.py sdist` and then installing the resulting .whl file.

**Comment by AndKe** [comment]
Yes, I haven't seen this issue since then, it is no longer an issue.
