### ISSUE TITLE
Warning In function 'py_mavlink_parse_char'

### ISSUE THREAD

**Issue by estechnical** [ArduPilot/MAVProxy#478]
```
mavnative/mavnative.c: In function 'py_mavlink_parse_char':
mavnative/mavnative.c:155:5: warning: enumeration value 'MAVLINK_PARSE_STATE_GOT_BAD_CRC1' not handled in switch [-Wswitch]
     switch (status->parse_state)
     ^~~~~~
```
It looks like this ought to be handled properly.

**Comment by peterbarker** [comment]
On Thu, 21 Dec 2017, Ed Simmons wrote:

> mavnative/mavnative.c: In function 'py_mavlink_parse_char':
> mavnative/mavnative.c:155:5: warning: enumeration value 'MAVLINK_PARSE_STAT
> E_GOT_BAD_CRC1' not handled in switch [-Wswitch]
>      switch (status->parse_state)
>      ^~~~~~
> 
> It looks like this ought to be handled properly.

Welll... no, not really.

This is where we handle the case that the first checksum byte doesn't 
match:

https://github.com/ArduPilot/pymavlink/blob/master/mavnative/mavnative.c#L253

We check to see which state to go to based on the current byte.

If we were to add a state for MAVLINK_PARSE_STATE_GOT_BAD_CRC1 then we may 
unnecessarily drop an entire packet (because we'd be dropping the stx 
which was received out-of-place).  Or we'd have to do some sort of redo of 
the switch which would be nasty.

I think the best way forward here is to squelch the warning; drop a case 
down in which basically explained why the state isn't required, and throw 
whatever error we can if we do hit that state.

We can't remove the define as it is part of the API.
