### ISSUE TITLE
MAVExplorer selection feature not working for MAGFIT

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/MAVProxy#841]
zooming on a graph region and then applying MAGFIT tool does not work

video of issue: https://www.dropbox.com/s/26kt3gaaoonm0j4/explorer.mp4?dl=0
log used: https://www.dropbox.com/s/19ssv36jykp8s7u/TVBS%20Roll%20issue.bin?dl=0

**Comment by srmainwaring** [comment]
On macOS / Windows where multiprocessing uses `spawn` I suspect this issue is arising from some of the state of MAVExplorer not being passed to the child process.

Tools such as `magfit` and `fft` are passed a function `timestamp_in_range` that references the globals `xlim_low` and `xlim_high`. These are updated in the main loop, however the child process (running `magfit` say) gets a separate uninitialised copy of these globals and so defaults to using the entire range.

The solution will involve passing the full state of the time limits to the child process - promoting the function `timestamp_in_range` to be a class encapsulating the limits would be one approach.

**Comment by srmainwaring** [comment]
@Hwurzburg there's a fix for this in PR https://github.com/ArduPilot/MAVProxy/pull/844. The same PR should enable the tools FFT, MAGFIT, and Stats for macOS and Windows.
